#!/bin/zsh
#nonos_sdk
#python esptool.py -b 921600 -p /dev/tty.usbserial-AL009REL write_flash 0x00000 ~/esp8266/esp8266_nonos_sdk/bin/eagle.flash.bin 0x10000 ~/esp8266/esp8266_nonos_sdk/bin/eagle.irom0text.bin

#rtos_sdk
sdk=~/esp8266/ESP8266_RTOS_SDK/bin
com=/dev/tty.usbserial-AL009REL
#~/esp8266/ESP8266_RTOS_SDK/websocket_demo/gen_misc.sh
./gen_misc.sh
python esptool.py -b 921600 -p "$com" write_flash 0x00000 "$sdk"/eagle.flash.bin 0x20000 "$sdk"/eagle.irom0text.bin 0x3fc000 "$sdk"/esp_init_data_default.bin 0x3fe000 "$sdk"/blank.bin
